version: 0.0
os: linux
hooks:
  ApplicationStop:
    - location: scripts/stop_service.sh
      timeout: 120
      runas: root
    - location: scripts/kill_service.sh
      timeout: 120
      runas: root
  AfterInstall:
    - location: init.sh
      timeout: 600
      runas: root
  ApplicationStart:
    - location: scripts/start_service.sh
      timeout: 120
      runas: root
    #- location: wait_for_service.sh
    #  timeout: 600
    #  runas: root
    #- location: register_with_elb.sh
    #  timeout: 120
    #  runas: root
